[build]
  command = "npm run build" # the command you run to build this file
  publish = "build" # create-react-app builds to this folder, Netlify should serve all these files statically

[functions]
  directory = "functions"
  node_bundler = "esbuild" # use esbuild to bundle functions
  external_node_modules = ["@sparticuz/chromium"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200